# Generated by Django 5.1.2 on 2024-10-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_hora", models.DateTimeField()),
                ("endereco", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("limite_convidados", models.PositiveIntegerField()),
                (
                    "visibilidade",
                    models.CharField(
                        choices=[("publico", "Público"), ("privado", "Privado")],
                        max_length=7,
                    ),
                ),
            ],
        ),
    ]
