# Generated by Django 5.1.2 on 2024-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
