# Generated by Django 5.1.2 on 2024-10-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_perfil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfil",
            old_name="user",
            new_name="usuario",
        ),
    ]
