# Generated by Django 5.1.2 on 2024-10-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_rename_user_perfil_usuario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Perfil",
        ),
    ]
